move pkg installer script

diff --git a/.data/source.yaml b/.data/source.yaml
--- a/.data/source.yaml
+++ b/.data/source.yaml
@@ -2022,99 +2022,109 @@ devcontainer:
                   "https://github.com/prefix-dev/pixi/releases/download/v${VERSION}/pixi-$(uname -m)-unknown-linux-musl"
                 chmod +x "$pixi_bin"
                 pixi info
-    # pkg_setup:
-    #   metadata:
-    #     name: Package Setup
-    #     version: 0.1.0
-    #     description: Install local packages in development mode.
-    #     installsAfter:
-    #       - ghcr.io/devcontainers/features/common-utils
-    #       - ghcr.io/devcontainers/features/conda
-    #     postStartCommand: "/usr/local/share/app_installation/post-start-command.sh"
-    #     options:
-    #       packages:
-    #         type: string
-    #         description: >-
-    #           Packages to install.
-    #           This must be a string representing a JSON object,
-    #           where keys are the name of Conda environments to use for installation.
-    #           Each value is a JSON object with a key "packages",
-    #           and optionally "python-version", and "sources",
-    #           corresponding to the package installation script's input arguments.
-    #           Note that quotes inside the JSON string must be escaped with triple backslashes.
-    #         default: ""
-    #       script_filepath:
-    #         type: string
-    #         description: Absolute path to the installation script file.
-    #         default: /usr/local/share/app_installation/install.py
-    #       metadata_filepath:
-    #         type: string
-    #         description: Absolute path to the project metadata file.
-    #         default: /usr/local/share/app_installation/metadata.json
-    #   install: |
-    #     #!/usr/bin/env bash
-    #     set -euxo pipefail
+    installer:
+      metadata:
+        content:
+          name: Package Setup
+          version: 0.1.0
+          description: Install local packages in development mode.
+          installsAfter:
+            - ghcr.io/devcontainers/features/common-utils
+            - ghcr.io/devcontainers/features/conda
+          postStartCommand: "/usr/local/share/app_installation/post-start-command.sh"
+          options:
+            packages:
+              type: string
+              description: >-
+                Packages to install.
+                This must be a string representing a JSON object,
+                where keys are the name of Conda environments to use for installation.
+                Each value is a JSON object with a key "packages",
+                and optionally "python-version", and "sources",
+                corresponding to the package installation script's input arguments.
+                Note that quotes inside the JSON string must be escaped with triple backslashes.
+              default: ""
+            script_filepath:
+              type: string
+              description: Absolute path to the installation script file.
+              default: /usr/local/share/app_installation/install.py
+            metadata_filepath:
+              type: string
+              description: Absolute path to the project metadata file.
+              default: /usr/local/share/app_installation/metadata.json
+      install:
+        content:
+          body:
+            - content: |
+                #!/usr/bin/env bash
+                set -euxo pipefail
 
-    #     # Redirect stdout and stderr to a file
-    #     echo "Creating log directory..."
-    #     mkdir -p "$LOG_DIRPATH"
-    #     LOG_FILE="${LOG_DIRPATH}/install.log"
-    #     exec > >(tee -a "$LOG_FILE") 2>&1
+                # Redirect stdout and stderr to a file
+                echo "Creating log directory..."
+                mkdir -p "$LOG_DIRPATH"
+                LOG_FILE="${LOG_DIRPATH}/install.log"
+                exec > >(tee -a "$LOG_FILE") 2>&1
 
-    #     # Create postStartCommand script
-    #     POST_START_SCRIPT_DIRPATH="/usr/local/share/app_installation"
-    #     POST_START_SCRIPT_FILEPATH="${POST_START_SCRIPT_DIRPATH}/post-start-command.sh"
-    #     mkdir -p "$POST_START_SCRIPT_DIRPATH"
-    #     {
-    #       echo '#!/usr/bin/env bash'
-    #       echo 'set -euxo pipefail'
-    #     } > "$POST_START_SCRIPT_FILEPATH"
-    #     chmod +x "$POST_START_SCRIPT_FILEPATH"
+                # Create postStartCommand script
+                POST_START_SCRIPT_DIRPATH="/usr/local/share/app_installation"
+                POST_START_SCRIPT_FILEPATH="${POST_START_SCRIPT_DIRPATH}/post-start-command.sh"
+                mkdir -p "$POST_START_SCRIPT_DIRPATH"
+                {
+                  echo '#!/usr/bin/env bash'
+                  echo 'set -euxo pipefail'
+                } > "$POST_START_SCRIPT_FILEPATH"
+                chmod +x "$POST_START_SCRIPT_FILEPATH"
 
-    #     echo "Initializing conda..."
-    #     conda init
+                echo "Initializing conda..."
+                conda init
 
-    #     if ! echo "$PACKAGES" | jq empty; then
-    #         echo "Invalid JSON in PACKAGES"
-    #         exit 1
-    #     fi
+                if ! echo "$PACKAGES" | jq empty; then
+                    echo "Invalid JSON in PACKAGES"
+                    exit 1
+                fi
 
-    #     for conda_env_name in $(echo "$PACKAGES" | jq -r 'keys[]'); do
-    #         value=$(echo "$PACKAGES" | jq -c --arg k "$conda_env_name" '.[$k]')
-    #         packages=$(echo "$value" | jq -c '.packages')
+                for conda_env_name in $(echo "$PACKAGES" | jq -r 'keys[]'); do
+                    value=$(echo "$PACKAGES" | jq -c --arg k "$conda_env_name" '.[$k]')
+                    packages=$(echo "$value" | jq -c '.packages')
 
-    #         # Build the base command
-    #         cmd=(
-    #           python "$SCRIPT_FILEPATH"
-    #             --conda-env-name "$conda_env_name"
-    #             --packages "$packages"
-    #             --filepath "$METADATA_FILEPATH"
-    #             --no-self
-    #         )
+                    # Build the base command
+                    cmd=(
+                      python "$SCRIPT_FILEPATH"
+                        --conda-env-name "$conda_env_name"
+                        --packages "$packages"
+                        --filepath "$METADATA_FILEPATH"
+                        --no-self
+                    )
 
-    #         # Optionally add --python-version
-    #         if echo "$value" | jq -e 'has("python-version")' > /dev/null; then
-    #             python_version=$(echo "$value" | jq -r '.["python-version"]')
-    #             cmd+=(--python-version "$python_version")
-    #         fi
+                    # Optionally add --python-version
+                    if echo "$value" | jq -e 'has("python-version")' > /dev/null; then
+                        python_version=$(echo "$value" | jq -r '.["python-version"]')
+                        cmd+=(--python-version "$python_version")
+                    fi
 
-    #         # Optionally add --sources
-    #         if echo "$value" | jq -e 'has("sources")' > /dev/null; then
-    #             sources=$(echo "$value" | jq -r '.sources')
-    #             cmd+=(--sources $sources)
-    #         fi
+                    # Optionally add --sources
+                    if echo "$value" | jq -e 'has("sources")' > /dev/null; then
+                        sources=$(echo "$value" | jq -r '.sources')
+                        cmd+=(--sources $sources)
+                    fi
 
-    #         # Capture and write command output
-    #         output=$("${cmd[@]}")
+                    # Capture and write command output
+                    output=$("${cmd[@]}")
 
-    #         # Append output to the file
-    #         while IFS= read -r line; do
-    #             echo "$line" >> "$POST_START_SCRIPT_FILEPATH"
-    #         done <<< "$output"
-    #     done
+                    # Append output to the file
+                    while IFS= read -r line; do
+                        echo "$line" >> "$POST_START_SCRIPT_FILEPATH"
+                    done <<< "$output"
+                done
 
-    #     echo "Cleaning up cache..."
-    #     conda clean --all -y
+                echo "Cleaning up cache..."
+                conda clean --all -y
+      install_py:
+        name: Python Installation Script
+        summary: Python script to install packages from this repository.
+        status: inactive
+        type: txt
+        relpath: install.py
     # user_setup:
     #   # https://github.com/devcontainers/images/blob/main/src/universal/.devcontainer/local-features/setup-user/
     #   metadata:
