change devcontainer image from universal to ubuntu
The universal devcontainer image (https://github.com/devcontainers/images/blob/main/src/universal/) installs the docker-in-docker feature (https://github.com/devcontainers/features/tree/main/src/docker-in-docker), which is incompatible with the docker-outside-of-docker feature (https://github.com/devcontainers/features/tree/main/src/docker-outside-of-docker) (see  https://github.com/devcontainers/features/issues/742#issuecomment-1793019485). The latter is required to run commands in other devcontainers from the main container.

Additionally, the universal image install jupyterlab, which causes some conflicts with the jupyterlab installed by conda. The observed conflict was with the jupyterlab-git extension, where the frontend and backend versions don't match.

diff --git a/.control/dev.yaml b/.control/dev.yaml
--- a/.control/dev.yaml
+++ b/.control/dev.yaml
@@ -238,6 +238,128 @@ devfeature_conda_setup:
     fi
     echo "Cleaning up cache..."
     conda clean --all -y
+devfeature_user_setup:
+  # https://github.com/devcontainers/images/blob/main/src/universal/.devcontainer/local-features/setup-user/
+  feature:
+    id: setup-user
+    name: Setup user configs
+    version: "0.1.0"
+    containerEnv:
+      RUBY_HOME: /usr/local/rvm/rubies/default
+      JAVA_ROOT: /home/codespace/java
+      NODE_ROOT: /home/codespace/nvm
+      PHP_ROOT: /home/codespace/.php
+      PYTHON_ROOT: /home/codespace/.python
+      RUBY_ROOT: /home/codespace/.ruby
+      MAVEN_ROOT: /home/codespace/.maven
+      HUGO_ROOT: /home/codespace/.hugo
+      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
+      NUGET_XMLDOC_MODE: skip
+      ORYX_ENV_TYPE: vsonline-present
+      PYTHONIOENCODING: UTF-8
+      NPM_GLOBAL: /home/codespace/.npm-global
+      NVS_HOME: /home/codespace/.nvs
+      RVM_PATH: /usr/local/rvm
+      RAILS_DEVELOPMENT_HOSTS: .githubpreview.dev,.preview.app.github.dev,.app.github.dev
+      GOROOT: /usr/local/go
+      JUPYTERLAB_PATH: /home/codespace/.local/bin
+      PATH: /home/codespace/.dotnet:/home/codespace/nvm/current/bin:/home/codespace/.php/current/bin:/home/codespace/.python/current/bin:/home/codespace/java/current/bin:/home/codespace/.ruby/current/bin:/home/codespace/.local/bin:${PATH}
+  install: |
+    #!/usr/bin/env bash
+
+    USERNAME=${USERNAME:-"codespace"}
+
+    set -eux
+
+    if [ "$(id -u)" -ne 0 ]; then
+        echo -e 'Script must be run as root. Use sudo, su, or add "USER root" to your Dockerfile before running this script.'
+        exit 1
+    fi
+
+    # Ensure that login shells get the correct path if the user updated the PATH using ENV.
+    rm -f /etc/profile.d/00-restore-env.sh
+    echo "export PATH=${PATH//$(sh -lc 'echo $PATH')/\$PATH}" > /etc/profile.d/00-restore-env.sh
+    chmod +x /etc/profile.d/00-restore-env.sh
+
+    export DEBIAN_FRONTEND=noninteractive
+
+    sudo_if() {
+        COMMAND="$*"
+        if [ "$(id -u)" -eq 0 ] && [ "$USERNAME" != "root" ]; then
+            su - "$USERNAME" -c "$COMMAND"
+        else
+            "$COMMAND"
+        fi
+    }
+
+    # Enables the oryx tool to generate manifest-dir which is needed for running the postcreate tool
+    DEBIAN_FLAVOR="focal-scm"
+    mkdir -p /opt/oryx && echo "vso-focal" > /opt/oryx/.imagetype
+    echo "DEBIAN|${DEBIAN_FLAVOR}" | tr '[a-z]' '[A-Z]' > /opt/oryx/.ostype
+
+    # Oryx expects the tool to be installed at `/opt/oryx` and looks for relevant files in there.
+    ln -snf /usr/local/oryx/* /opt/oryx
+
+    # For the universal image, oryx build tool installs the detected platforms in /home/codespace/*. Hence, linking current platforms to the /home/codespace/ path and adding it to the PATH.
+    # This ensures that whatever platfornm versions oryx detects and installs are set as root.
+    NODE_PATH="/home/codespace/nvm/current"
+    ln -snf /usr/local/share/nvm /home/codespace
+
+    PHP_PATH="/home/${USERNAME}/.php/current"
+    mkdir -p /home/${USERNAME}/.php
+    ln -snf /usr/local/php/current $PHP_PATH
+
+    PYTHON_PATH="/home/${USERNAME}/.python/current"
+    mkdir -p /home/${USERNAME}/.python
+    ln -snf /usr/local/python/current $PYTHON_PATH
+    ln -snf /usr/local/python /opt/python
+
+    JAVA_PATH="/home/codespace/java/current"
+    ln -snf /usr/local/sdkman/candidates/java /home/codespace
+
+    RUBY_PATH="/home/${USERNAME}/.ruby/current"
+    mkdir -p /home/${USERNAME}/.ruby
+    ln -snf /usr/local/rvm/rubies/default $RUBY_PATH
+
+    DOTNET_PATH="/home/${USERNAME}/.dotnet"
+
+    # Required due to https://github.com/devcontainers/features/pull/628/files#r1276659825
+    chown -R "${USERNAME}:${USERNAME}" /usr/share/dotnet
+    chmod g+r+w+s /usr/share/dotnet
+    chmod -R g+r+w /usr/share/dotnet
+
+    ln -snf /usr/share/dotnet $DOTNET_PATH
+    mkdir -p /opt/dotnet/lts
+    cp -R /usr/share/dotnet/dotnet /opt/dotnet/lts
+    cp -R /usr/share/dotnet/LICENSE.txt /opt/dotnet/lts
+    cp -R /usr/share/dotnet/ThirdPartyNotices.txt /opt/dotnet/lts
+
+    MAVEN_PATH="/home/${USERNAME}/.maven/current"
+    mkdir -p /home/${USERNAME}/.maven
+    ln -snf /usr/local/sdkman/candidates/maven/current $MAVEN_PATH
+
+    HUGO_ROOT="/home/${USERNAME}/.hugo/current"
+    mkdir -p /home/${USERNAME}/.hugo
+    ln -snf /usr/local/hugo $HUGO_ROOT
+
+    HOME_DIR="/home/${USERNAME}/"
+    chown -R ${USERNAME}:${USERNAME} ${HOME_DIR}
+    chmod -R g+r+w "${HOME_DIR}"
+    find "${HOME_DIR}" -type d | xargs -n 1 chmod g+s
+
+    OPT_DIR="/opt/"
+    chown -R ${USERNAME}:oryx ${OPT_DIR}
+    chmod -R g+r+w "${OPT_DIR}"
+    find "${OPT_DIR}" -type d | xargs -n 1 chmod g+s
+
+    echo "Defaults secure_path=\"${DOTNET_PATH}:${NODE_PATH}/bin:${PHP_PATH}/bin:${PYTHON_PATH}/bin:${JAVA_PATH}/bin:${RUBY_PATH}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/usr/local/share:/home/${USERNAME}/.local/bin:${PATH}\"" >> /etc/sudoers.d/$USERNAME
+
+    # Temporary: Due to GHSA-c2qf-rxjj-qqgw
+    bash -c ". /usr/local/share/nvm/nvm.sh && nvm use 22"
+    bash -c "npm -g install -g npm@9.8.1"
+    bash -c ". /usr/local/share/nvm/nvm.sh && nvm use stable"
+
+    echo "Done!"
 devcontainer:
   docker-compose:
     config:
@@ -260,14 +382,144 @@ devcontainer_main:
   service:
     privileged: true  # Required to use Docker in Docker.
   dockerfile:
-    - FROM mcr.microsoft.com/devcontainers/universal:2-linux
+    # https://hub.docker.com/_/ubuntu
+    - FROM ubuntu:noble
+    # https://github.com/devcontainers/images/blob/main/src/base-ubuntu/.devcontainer/Dockerfile
+    - |
+      RUN if id "ubuntu" &>/dev/null; then \
+              echo "Deleting user 'ubuntu'" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user."; \
+          else \
+              echo "User 'ubuntu' does not exist."; \
+          fi
+    # https://github.dev/devcontainers/images/tree/main/src/universal/.devcontainer
+    - |
+      RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
+          # Restore man command
+          && yes | unminimize 2>&1
+
+      ENV LANG="C.UTF-8"
+
+      # Install basic build tools
+      RUN apt-get update \
+          && apt-get upgrade -y \
+          && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
+              make \
+              unzip \
+              # The tools in this package are used when installing packages for Python
+              build-essential \
+              swig3.0 \
+              # Required for Microsoft SQL Server
+              unixodbc-dev \
+              # Required for PostgreSQL
+              libpq-dev \
+              # Required for mysqlclient
+              default-libmysqlclient-dev \
+              # Required for ts
+              moreutils \
+              rsync \
+              zip \
+              libgdiplus \
+              jq \
+              # By default pip is not available in the buildpacks image
+              python3-pip-whl \
+              python3-pip \
+              #.NET Core related pre-requisites
+              libc6 \
+              libgcc1 \
+              libgssapi-krb5-2 \
+              libncurses6 \
+              liblttng-ust1 \
+              libssl-dev \
+              libstdc++6 \
+              zlib1g \
+              libuuid1 \
+              libunwind8 \
+              sqlite3 \
+              libsqlite3-dev \
+              software-properties-common \
+              tk-dev \
+              uuid-dev \
+              curl \
+              gettext \
+              inotify-tools \
+          && rm -rf /var/lib/apt/lists/* \
+          # This is the folder containing 'links' to benv and build script generator
+          && apt-get update \
+          && apt-get upgrade -y \
+          && add-apt-repository universe \
+          && rm -rf /var/lib/apt/lists/*
+
+      # Verify expected build and debug tools are present
+      RUN apt-get update \
+          && apt-get -y install build-essential cmake cppcheck valgrind clang lldb llvm gdb python3-dev \
+          # Install tools and shells not in common script
+          && apt-get install -yq vim vim-doc xtail software-properties-common libsecret-1-dev \
+          # Install additional tools (useful for 'puppeteer' project)
+          && apt-get install -y --no-install-recommends libnss3 libnspr4 libatk-bridge2.0-0 libatk1.0-0 libx11-6 libpangocairo-1.0-0 \
+                                                        libx11-xcb1 libcups2 libxcomposite1 libxdamage1 libxfixes3 libpango-1.0-0 libgbm1 libgtk-3-0 \
+          # Clean up
+          && apt-get autoremove -y && apt-get clean -y \
+
+      # Default to bash shell (other shells available at /usr/bin/fish and /usr/bin/zsh)
+      ENV SHELL=/bin/bash \
+          DOCKER_BUILDKIT=1
+
+      # Install and setup fish
+      RUN apt-get install -yq fish \
+          && FISH_PROMPT="function fish_prompt\n    set_color green\n    echo -n (whoami)\n    set_color normal\n    echo -n \":\"\n    set_color blue\n    echo -n (pwd)\n    set_color normal\n    echo -n \"> \"\nend\n" \
+          && printf "$FISH_PROMPT" >> /etc/fish/functions/fish_prompt.fish \
+          && printf "if type code-insiders > /dev/null 2>&1; and not type code > /dev/null 2>&1\n  alias code=code-insiders\nend" >> /etc/fish/conf.d/code_alias.fish
+
+      # Remove scripts now that we're done with them
+      RUN apt-get clean -y
+
+      CMD [ "sleep", "infinity" ]
     - ${{ __temp__.dockerfile_copy_env_cmd }}$
     - ${{ __temp__.dockerfile_copy_script_cmd }}$
   container:
     name: Main Development Environment
+    remoteUser: codespace
+    containerUser: codespace
     forwardPorts:
       - 8888:8888  # for Jupyter Notebook
     features:
+      # https://github.com/devcontainers/features/tree/main/src/common-utils
+      ghcr.io/devcontainers/features/common-utils:2:
+        installZsh: true
+        configureZshAsDefaultShell: false
+        installOhMyZsh: true
+        installOhMyZshConfig: true
+        upgradePackages: true
+        username: codespace
+        userUid: "1000"
+        userGid: "1000"
+      # https://github.com/devcontainers/features/tree/main/src/conda
+      ghcr.io/devcontainers/features/conda:1:
+        version: latest
+        addCondaForge: true
+      # https://github.com/devcontainers/features/tree/main/src/node
+      ghcr.io/devcontainers/features/node:1:
+        version: "22"
+        additionalVersions: "20"
+      # https://github.com/devcontainers/features/tree/main/src/sshd
+      ghcr.io/devcontainers/features/sshd:1:
+        version: latest
+      # https://github.com/devcontainers/features/tree/main/src/git
+      ghcr.io/devcontainers/features/git:1:
+        version: latest
+        ppa: false
+      # https://github.com/devcontainers/features/tree/main/src/git-lfs
+      ghcr.io/devcontainers/features/git-lfs:1:
+        version: latest
+        autoPull: true
+      # https://github.com/devcontainers/features/tree/main/src/github-cli
+      ghcr.io/devcontainers/features/github-cli:1:
+        version: latest
+      # https://github.com/devcontainers/features/tree/main/src/oryx
+      ghcr.io/devcontainers/features/oryx:1: {}
+      # https://github.com/devcontainers/features/tree/main/src/docker-outside-of-docker
+      # Note: This feature is incompatible with the Docker-in-Docker feature
+      # - https://github.com/devcontainers/features/issues/742#issuecomment-1793019485
       ghcr.io/devcontainers/features/docker-outside-of-docker:1: {}
       # https://github.com/devcontainers-extra/features/tree/main/src/apt-get-packages
       ghcr.io/devcontainers-extra/features/apt-get-packages:1:
@@ -275,8 +527,24 @@ devcontainer_main:
           #{{
             return ",".join([pkg["spec"]["full"] for pkg in get("devcontainer_main.apt", {}).values()])
           }}#
+      ./${{ devfeature_user_setup.path }}$: "latest"
       ./${{ devfeature_conda_setup.path }}$: {}
       ./${{ devfeature_pkg_setup.path }}$: {}
+    overrideFeatureInstallOrder:
+      - ghcr.io/devcontainers/features/common-utils
+      - ghcr.io/devcontainers/features/git
+      - ghcr.io/devcontainers/features/node
+      - ghcr.io/devcontainers/features/conda
+      - ghcr.io/devcontainers/features/python
+      - ghcr.io/devcontainers/features/sshd
+      - ghcr.io/devcontainers/features/git-lfs
+      - ghcr.io/devcontainers/features/github-cli
+      - ghcr.io/devcontainers/features/docker-outside-of-docker
+      - ghcr.io/devcontainers/features/oryx
+      - ./${{ devfeature_user_setup.path }}$
+      - ghcr.io/devcontainers-extra/features/apt-get-packages
+      - ./${{ devfeature_conda_setup.path }}$
+      - ./${{ devfeature_pkg_setup.path }}$
     postCreateCommand:
       pre_commit_install:
         - conda
