Update manager.yaml

diff --git a/.github/workflows/manager.yaml b/.github/workflows/manager.yaml
--- a/.github/workflows/manager.yaml
+++ b/.github/workflows/manager.yaml
@@ -11,49 +11,49 @@ on:
       zenodo-sandbox-token:
         description: Token for Zenodo Sandbox API.
         required: false
-    outputs:
-      web:
-        value: ${{ jobs.manager.outputs.web }}
-        description: Configurations for website job.
-      lint:
-        value: ${{ jobs.manager.outputs.lint }}
-        description: Configurations for lint job.
-      test:
-        value: ${{ jobs.manager.outputs.test }}
-        description: Configurations for test job.
-      build:
-        value: ${{ jobs.manager.outputs.build }}
-        description: Configurations for build job.
-      binder:
-        value: ${{ jobs.manager.outputs.binder }}
-        description: Configurations for binder job.
-      publish-testpypi:
-        value: ${{ jobs.manager.outputs.publish-testpypi }}
-        description: Configurations for publish-testpypi job.
-      publish-pypi:
-        value: ${{ jobs.manager.outputs.publish-pypi }}
-        description: Configurations for publish-pypi job.
-      publish-anaconda:
-        value: ${{ jobs.manager.outputs.publish-anaconda }}
-        description: Configurations for publish-anaconda job.
-      release:
-        value: ${{ jobs.manager.outputs.release }}
-        description: Configurations for release job.
+#    outputs:
+#      web:
+#        value: ${{ jobs.manager.outputs.web }}
+#        description: Configurations for website job.
+#      lint:
+#        value: ${{ jobs.manager.outputs.lint }}
+#        description: Configurations for lint job.
+#      test:
+#        value: ${{ jobs.manager.outputs.test }}
+#        description: Configurations for test job.
+#      build:
+#        value: ${{ jobs.manager.outputs.build }}
+#        description: Configurations for build job.
+#      binder:
+#        value: ${{ jobs.manager.outputs.binder }}
+#        description: Configurations for binder job.
+#      publish-testpypi:
+#        value: ${{ jobs.manager.outputs.publish-testpypi }}
+#        description: Configurations for publish-testpypi job.
+#      publish-pypi:
+#        value: ${{ jobs.manager.outputs.publish-pypi }}
+#        description: Configurations for publish-pypi job.
+#      publish-anaconda:
+#        value: ${{ jobs.manager.outputs.publish-anaconda }}
+#        description: Configurations for publish-anaconda job.
+#      release:
+#        value: ${{ jobs.manager.outputs.release }}
+#        description: Configurations for release job.
 jobs:
   manager:
     name: Manager
     runs-on: ubuntu-latest
-    outputs:
-      fail: ${{ steps.proman.outputs.fail }}
-      web: ${{ steps.proman.outputs.web }}
-      lint: ${{ steps.proman.outputs.lint }}
-      test: ${{ steps.proman.outputs.test }}
-      build: ${{ steps.proman.outputs.build }}
-      binder: ${{ steps.proman.outputs.binder }}
-      publish-testpypi: ${{ steps.proman.outputs.publish-testpypi }}
-      publish-pypi: ${{ steps.proman.outputs.publish-pypi }}
-      publish-anaconda: ${{ steps.proman.outputs.publish-anaconda }}
-      release: ${{ steps.proman.outputs.release }}
+#    outputs:
+#      fail: ${{ steps.proman.outputs.fail }}
+#      web: ${{ steps.proman.outputs.web }}
+#      lint: ${{ steps.proman.outputs.lint }}
+#      test: ${{ steps.proman.outputs.test }}
+#      build: ${{ steps.proman.outputs.build }}
+#      binder: ${{ steps.proman.outputs.binder }}
+#      publish-testpypi: ${{ steps.proman.outputs.publish-testpypi }}
+#      publish-pypi: ${{ steps.proman.outputs.publish-pypi }}
+#      publish-anaconda: ${{ steps.proman.outputs.publish-anaconda }}
+#      release: ${{ steps.proman.outputs.release }}
     env:
       PATH_REPO_BASE: repo_base
       PATH_REPO_HEAD: repo_head
@@ -81,21 +81,21 @@ jobs:
         with:
           repo_path: ${{ env.PATH_REPO_HEAD }}
           load_cache: 'true'
-      - name: Report Upload
-        uses: actions/upload-artifact@v4
-        with:
-          path: ${{ steps.setup.outputs.report_dirpath }}
-          name: Reports
-  status:
-    name: Status
-    runs-on: ubuntu-latest
-    needs: manager
-    steps:
-      - name: Status Check
-        run: |
-          if [ "${{ needs.manager.outputs.fail }}" = "true" ]; then
-            exit 1
-          else
-            exit 0
-          fi
+#      - name: Report Upload
+#        uses: actions/upload-artifact@v4
+#        with:
+#          path: ${{ steps.setup.outputs.report_dirpath }}
+#          name: Reports
+#  status:
+#    name: Status
+#    runs-on: ubuntu-latest
+#    needs: manager
+#    steps:
+#      - name: Status Check
+#        run: |
+#          if [ "${{ needs.manager.outputs.fail }}" = "true" ]; then
+#            exit 1
+#          else
+#            exit 0
+#          fi
 
