update

diff --git a/.github/workflows/package_lint.yaml b/.github/workflows/package_lint.yaml
--- a/.github/workflows/package_lint.yaml
+++ b/.github/workflows/package_lint.yaml
@@ -135,62 +135,62 @@ jobs:
           category: "/language:${{matrix.language}}"
 
 
-  bandit:
-    # Bandit is a security linter designed to find common security issues in Python code.
-    # This action will run Bandit on your codebase.
-    # The results of the scan will be found under the Security tab of your repository.
-    # Adapted from GitHub starter workflow, e.g.:
-    #  https://github.com/Armin-Ariamajd/PyPACKIT/new/main?filename=.github%2Fworkflows%2Fbandit.yml&workflow_template=code-scanning%2Fbandit
-    # Refs:
-    #  https://github.com/marketplace/actions/bandit-scan
-    #  https://pypi.org/project/bandit/
-    name: 'Run bandit'
-    permissions:
-      contents: read # for actions/checkout to fetch code
-      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
-      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
-    runs-on: ubuntu-latest
-    steps:
-      - name: 'Checkout repository'
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ inputs.checkout-ref }}
-
-      - name: 'Bandit Scan'
-        uses: shundor/python-bandit-scan@v1.0
-        with:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information.
-          path: .
-
-
-  pyre:
-    # Pyre is a performant type checker for Python compliant with
-    # PEP 484. Pyre can analyze codebases with millions of lines
-    # of code incrementally – providing instantaneous feedback
-    # to developers as they write code.
-
-    # Adapted from GitHub starter workflow, e.g.:
-    #  https://github.com/Armin-Ariamajd/PyPACKIT/new/main?filename=.github%2Fworkflows%2Fpyre.yml&workflow_template=code-scanning%2Fpyre
-    # Refs:
-    #  https://github.com/facebook/pyre-action
-    #  https://pyre-check.org
-    name: 'Run Pyre'
-    permissions:
-      actions: read
-      contents: read
-      security-events: write
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          submodules: true
-          ref: ${{ inputs.checkout-ref }}
-
-      - name: Run Pyre
-        uses: facebook/pyre-action@v0.0.1
-        with:
-          repo-directory: './'
-          requirements-path: 'requirements.txt'
+#  bandit:
+#    # Bandit is a security linter designed to find common security issues in Python code.
+#    # This action will run Bandit on your codebase.
+#    # The results of the scan will be found under the Security tab of your repository.
+#    # Adapted from GitHub starter workflow, e.g.:
+#    #  https://github.com/Armin-Ariamajd/PyPACKIT/new/main?filename=.github%2Fworkflows%2Fbandit.yml&workflow_template=code-scanning%2Fbandit
+#    # Refs:
+#    #  https://github.com/marketplace/actions/bandit-scan
+#    #  https://pypi.org/project/bandit/
+#    name: 'Run bandit'
+#    permissions:
+#      contents: read # for actions/checkout to fetch code
+#      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
+#      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: 'Checkout repository'
+#        uses: actions/checkout@v3
+#        with:
+#          ref: ${{ inputs.checkout-ref }}
+#
+#      - name: 'Bandit Scan'
+#        uses: shundor/python-bandit-scan@v1.0
+#        with:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information.
+#          path: .
+#
+#
+#  pyre:
+#    # Pyre is a performant type checker for Python compliant with
+#    # PEP 484. Pyre can analyze codebases with millions of lines
+#    # of code incrementally – providing instantaneous feedback
+#    # to developers as they write code.
+#
+#    # Adapted from GitHub starter workflow, e.g.:
+#    #  https://github.com/Armin-Ariamajd/PyPACKIT/new/main?filename=.github%2Fworkflows%2Fpyre.yml&workflow_template=code-scanning%2Fpyre
+#    # Refs:
+#    #  https://github.com/facebook/pyre-action
+#    #  https://pyre-check.org
+#    name: 'Run Pyre'
+#    permissions:
+#      actions: read
+#      contents: read
+#      security-events: write
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v3
+#        with:
+#          submodules: true
+#          ref: ${{ inputs.checkout-ref }}
+#
+#      - name: Run Pyre
+#        uses: facebook/pyre-action@v0.0.1
+#        with:
+#          repo-directory: './'
+#          requirements-path: 'requirements.txt'
 
 
   mypy:
@@ -457,25 +457,25 @@ jobs:
           jupyter: true
 
 
-  git-attributes:
-    # Check if all files have a corresponding rule in the '.gitattributes' file.
-    name: 'Check .gitattributes'
-    runs-on: ubuntu-latest
-    steps:
-      - name: 'Checkout repository'
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ inputs.checkout-ref }}
-
-      - name: 'Check .gitattributes'
-        # Ref: https://github.com/alexkaratarakis/gitattributes/tree/master#ci-step
-        run: |
-          missing_attributes=$(git ls-files | git check-attr -a --stdin | grep "text: auto")
-          if [[ "$missing_attributes" ]]; then
-            echo ".gitattributes rule missing for the following files:";
-            echo "$missing_attributes";
-            exit 1;
-          else
-            echo "All files have a corresponding rule in .gitattributes";
-            exit 0;
-          fi
+#  git-attributes:
+#    # Check if all files have a corresponding rule in the '.gitattributes' file.
+#    name: 'Check .gitattributes'
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: 'Checkout repository'
+#        uses: actions/checkout@v3
+#        with:
+#          ref: ${{ inputs.checkout-ref }}
+#
+#      - name: 'Check .gitattributes'
+#        # Ref: https://github.com/alexkaratarakis/gitattributes/tree/master#ci-step
+#        run: |
+#          missing_attributes=$(git ls-files | git check-attr -a --stdin | grep "text: auto")
+#          if [[ "$missing_attributes" ]]; then
+#            echo ".gitattributes rule missing for the following files:";
+#            echo "$missing_attributes";
+#            exit 1;
+#          else
+#            echo "All files have a corresponding rule in .gitattributes";
+#            exit 0;
+#          fi
